spring:
  datasource:
    druid:
      # 监控配置
      # WebStatFilter配置
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
      # StatViewServlet配置
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        allow: 127.0.0.1
        deny: 192.168.0.0
        login-username: admin
        login-password: admin
        reset-enable: false
      filter:
        log4j2:
          statement-executable-sql-log-enable: true  # 输出sql
        stat:
          log-slow-sql: true
          merge-sql: true
          slow-sql-millis: 3000
        config:
          enabled: true
      systemDB:
        name: systemDB
        # jdbc 配置
        url: jdbc:mysql://127.0.0.1:3306/system_db?useSSL=false&allowMultiQueries=true
        username: root
        password: f9TJLNZyP6z8zW/rbNOZieL3h8PdRrG8NTBVpV2t0bOgt//+RzDII1ubWmBM8DL1W0ky+9BE+8WoHAQE5l+9nA==
        public-key: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAKx6Dwr89NU1ByvlyffQMqaktSzPH3gXKx7yAKZ0jObFj50vS/I5/Yihe9TUbuWydI31rQBOwx4OFuGwgBwHC60CAwEAAQ==
        driver-class-name: com.mysql.jdbc.Driver
        # 连接池配置
        initial-size: 5
        max-active: 20
        max-wait: 60000 # 配置获取连接等待超时的时间
        min-idle: 5
        time-between-eviction-runs-millis: 60000 # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        min-evictable-idle-time-millis: 300000 # 配置一个连接在池中最小生存的时间，单位是毫秒
        validation-query: SELECT 'x'
        validation-query-timeout: 10000
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        pool-prepared-statements: true
        max-pool-prepared-statement-per-connection-size: 20
        filters: stat,wall,log4j2,config # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
        connection-properties: config.decrypt=true;config.decrypt.key=${spring.datasource.druid.systemDB.public-key} # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
        use-global-data-source-stat: true # 合并多个DruidDataSource的监控数据
      businessDB:
        name: businessDB
        # jdbc 配置
        url: jdbc:mysql://127.0.0.1:3306/business_db?useSSL=false&allowMultiQueries=true
        username: root
        password: f9TJLNZyP6z8zW/rbNOZieL3h8PdRrG8NTBVpV2t0bOgt//+RzDII1ubWmBM8DL1W0ky+9BE+8WoHAQE5l+9nA==
        public-key: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAKx6Dwr89NU1ByvlyffQMqaktSzPH3gXKx7yAKZ0jObFj50vS/I5/Yihe9TUbuWydI31rQBOwx4OFuGwgBwHC60CAwEAAQ==
        driver-class-name: com.mysql.jdbc.Driver
        # 连接池配置
        initial-size: 5
        max-active: 20
        max-wait: 60000 # 配置获取连接等待超时的时间
        min-idle: 5
        time-between-eviction-runs-millis: 60000 # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        min-evictable-idle-time-millis: 300000 # 配置一个连接在池中最小生存的时间，单位是毫秒
        validation-query: SELECT 'x'
        validation-query-timeout: 10000
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        pool-prepared-statements: true
        max-pool-prepared-statement-per-connection-size: 20
        filters: stat,wall,log4j2,config # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
        connection-properties: config.decrypt=true;config.decrypt.key=${spring.datasource.druid.businessDB.public-key} # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
        use-global-data-source-stat: true # 合并多个DruidDataSource的监控数据